version: '2'

services:
    db:
        container_name: task_db
        image: postgres:13
        volumes:
            - task_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=task_db
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
volumes:
    task_db: {}